#!/bin/sh
# powermenu

powermenu="\
zzzz		loginctl suspend
lock		slock	
reboot		loginctl reboot 
shutdown	loginctl poweroff"

choice="$(echo "$powermenu" | cut -d'	' -f 1 | dmenu -i -fn spleen:size=15)" 

`echo "$powermenu" | grep "^$choice	" | cut -d '	' -f2-`
