#!/bin/sh
# powermenu

powermenu="\
zzzz		systemctl suspend
lock		slock	
reboot		systemctl reboot 
shutdown	systemctl poweroff"

choice="$(echo "$powermenu" | cut -d'	' -f 1 | dmenu -i -fn terminus:size=14)" 

`echo "$powermenu" | grep "^$choice	" | cut -d '	' -f2-`
