#!/bin/bash
#quit dwm


chosen=$(echo -e "Cancel\nSuspend\nLock\nReboot\nPoweroff" | dmenu -i -fn Terminus:size=14.3)

if [ $chosen = "Suspend" ]; then
	loginctl suspend

elif [ $chosen = "Lock" ]; then
        slock

elif [ $chosen = "Reboot" ]; then
	loginctl reboot

elif [ $chosen = "Poweroff" ]; then
	loginctl poweroff
fi
